### ISSUE TITLE
Python 3.7 Module 

### ISSUE THREAD

**Issue by eAwlaqi** [icanhasfay/PyPwned#10] opened 2020-10-20 17:24 UTC
Hi there ! 

Hope you are doing well . 

I have been trying to connect to HIBP API for weeks , for some work purposes . 
All my attempts failed so far . Whatever module I install it gives me " Module not found "

I am trying to look up list of email addresses , if they have been compromised or not and get the website . 

I would appreciate your support with this.

Many thanks

**Comment by icanhasfay** [comment] 2020-11-13 19:48
Hey @eAwlaqi,

I just ran it successfully on python 3.8.6.

If you're getting module installation issues the problem may be with your environment rather than the package itself. 

I'm going to close this for now since I confirmed it's searching against emails. If you are still running into issues feel free to re-open this with more detailed information on the issue.

-Eric

**Closed as completed by icanhasfay** 2020-11-13 19:48 UTC
